name: Orchard Core Contrib Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build windows-latest
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.*
    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Checkout OrchardCoreContrib.App Repository
      uses: actions/checkout@v6
      with: 
          repository: OrchardCoreContrib/OrchardCoreContrib.App
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
    - name:  Update submodules  
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Commit and push changes  
      run: |
        git config user.name "Hisham Bin Ateya"
        git config user.email "hishamco_2007@yahoo.com"
        git add --all
        git commit -m "Update submodules" || echo "No changes to commit"
        git push
