name: Update OrchardCoreContrib.App Submodules

on:
  push:
    branches: [ "main" ]

jobs:
  update-submodules:
    name: Build windows-latest
    runs-on: windows-latest

    steps:
      - name: Checkout OrchardCoreContrib.App
        uses: actions/checkout@v6
        with:
          repository: OrchardCoreContrib/OrchardCoreContrib.App
          submodules: true
          token: ${{ secrets.OCC_TOKEN }}

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit and push changes
        env:
          SUBMODULE_TOKEN: ${{ secrets.OCC_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git diff --cached --quiet && exit 0
          git commit -m "Update submodules to latest versions"
          git remote set-url origin https://x-access-token:${OCC_TOKEN}@github.com/OrchardCoreContrib/OrchardCoreContrib.App.git
          git push origin HEAD:main